.test:
  image: docker:latest
  services:
    - name: docker:dind
      alias: thedockerhost
  variables:
    DOCKER_HOST: tcp://thedockerhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - df -h
    - docker run --privileged ubuntu df -h

start-crosscicd:
  image: alpine
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
  script: |
      curl -H "Authorization: token ${GITHUB_TOKEN}" \
      -H 'Accept: application/vnd.github.everest-preview+json' \
      "https://api.github.com/repos/${GITHUB_REPO}/dispatches" \
      -d '{"event_type": "gitlab_trigger_'${CI_PIPELINE_ID}'", "client_payload": {"registration_token": "'${GITLAB_REGISTRATION_TOKEN}'"}}'

github:
  extends: .test
  tags:
    - crosscicd

gitlab:
  extends: .test
  tags:
    - docker