.test:
  image: docker:latest
  script:
    - df -h
    - docker run --privileged ubuntu df -h

crosscicd:
  extends: .test
  tags:
    - crosscicd

linux:
  extends: .test
  tags:
    - linux

docker:
  extends: .test
  tags:
    - docker