crosscicd:
  services:
  - docker:dind
  script:
    - df -h
    - docker run --privileged ubuntu df -h
  tags:
    - crosscicd

linux:
  image: docker:latest
  services:
  - docker:dind
  script:
    - df -h
    - docker run --privileged ubuntu df -h
  tags:
    - linux

docker:
  image: docker:latest
  services:
  - docker:dind
  script:
    - df -h
    - docker run --privileged ubuntu df -h
  tags:
    - docker